function TMarkers = convertAsegAparc2Table(fname_aseg,fname_aparc_lh,fname_aparc_rh)
    % This function is charged of taking the features from the tables
    % extacted from the ADNI subjects and joining aseg (subcortical) +
    % + aparc (cortical) into a single table. Names are also given so
    % columns can be understoood.
    
    [aseg,~,asegcols] =  fast_ldtable(fname_aseg);    
    % convert column names into cell string
    asegcols=cellstr(asegcols);
    
    % Finding indexes of subcortical features
    id=[find(strcmp('Left-Hippocampus',asegcols)==1),...
        find(strcmp('Right-Hippocampus',asegcols)==1),...
        find(strcmp('EstimatedTotalIntraCranialVol',asegcols)==1),...
        find(strcmp('lhCortexVol',asegcols)==1),...
        find(strcmp('rhCortexVol',asegcols)==1),...%5
        find(strcmp('Left-Putamen',asegcols)==1),...
        find(strcmp('Right-Putamen',asegcols)==1),...
        find(strcmp('Left-Pallidum',asegcols)==1),...
        find(strcmp('Right-Pallidum',asegcols)==1),...
        find(strcmp('Left-Caudate',asegcols)==1),...%10
        find(strcmp('Right-Caudate',asegcols)==1),...
        find(strcmp('Left-Amygdala',asegcols)==1),...
        find(strcmp('Right-Amygdala',asegcols)==1),...
        ];
    
    %Asigning features and names to the TAseg table.
    HV = aseg(:,id);
    TAseg = table(HV(:,1), HV(:,2), HV(:,3), HV(:,4),...
        HV(:,5), HV(:,6), HV(:,7), HV(:,8),...
        HV(:,9), HV(:,10), HV(:,11), HV(:,12), HV(:,13),...
        'VariableNames',{'LHippVol','RHippVol','ICV','LCortVol',...
        'RCortVol','LPutamen','RPutamen','LPallidum',...
        'RPallidum','LCaudete','RCaudete','LAmygdala','RAmigdala'});
    
    [aparc_lh,~,aparc_lhcols] =  fast_ldtable(fname_aparc_lh);
    % convert column names into cell string
    aparc_lhcols=cellstr(aparc_lhcols);
    
    % Finding indexes of subcortical features from left hemisphere
    id_lh=[find(strcmp('lh_entorhinal_thickness',aparc_lhcols)==1),...
        find(strcmp('lh_temporalpole_thickness',aparc_lhcols)==1),...
        find(strcmp('lh_inferiortemporal_thickness',aparc_lhcols)==1),...
        find(strcmp('lh_middletemporal_thickness',aparc_lhcols)==1),...
        find(strcmp('lh_inferiorparietal_thickness',aparc_lhcols)==1),...
        find(strcmp('lh_superiorparietal_thickness',aparc_lhcols)==1),...
        find(strcmp('lh_precuneus_thickness',aparc_lhcols)==1),...
        find(strcmp('lh_posteriorcingulate_thickness',aparc_lhcols)==1),...
        find(strcmp('lh_MeanThickness_thickness',aparc_lhcols)==1)];
    
    [aparc_rh,~,aparc_rhcols] =  fast_ldtable(fname_aparc_rh);
    % convert column names into cell string
    aparc_rhcols=cellstr(aparc_rhcols);
    
    % Finding indexes of subcortical features from right hemisphere
    id_rh=[find(strcmp('rh_entorhinal_thickness',aparc_rhcols)==1),...
        find(strcmp('rh_temporalpole_thickness',aparc_rhcols)==1),...
        find(strcmp('rh_inferiortemporal_thickness',aparc_rhcols)==1),...
        find(strcmp('rh_middletemporal_thickness',aparc_rhcols)==1),...
        find(strcmp('rh_inferiorparietal_thickness',aparc_rhcols)==1),...
        find(strcmp('rh_superiorparietal_thickness',aparc_rhcols)==1),...
        find(strcmp('rh_precuneus_thickness',aparc_rhcols)==1),...
        find(strcmp('rh_posteriorcingulate_thickness',aparc_rhcols)==1),...
        find(strcmp('rh_MeanThickness_thickness',aparc_rhcols)==1)];
    
    
    % Asigning features and names to the TApar table.
    TH=[aparc_lh(:,id_lh),aparc_rh(:,id_rh)];
    TApar=table(TH(:,1), TH(:,10), TH(:,9), TH(:,18),...
        TH(:,2), TH(:,3), TH(:,4), TH(:,5),...
        TH(:,6), TH(:,7), TH(:,8), TH(:,11),...
        TH(:,12), TH(:,13), TH(:,14), TH(:,15), TH(:,16), TH(:,17),...
        'VariableNames',{'L_ECT','R_ECT','L_MT','R_MT',...
        'LtmpPole','LinfTmp','LmidTmp','LinfPar',...
        'LsupPar','Lprecu','LpostCing','RtmpPole',...
        'RinfTmp','RmidTmp','RinfPar','RsupPar','Rprecu','RpostCing'});
    
    % Joining both tables into a new one
    TMarkers=[TAseg,TApar];
end